/*    */ package com.daimler.cebas.certificates.control.vo;
/*    */ 
/*    */ import io.swagger.annotations.ApiModel;
/*    */ import io.swagger.annotations.ApiModelProperty;
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ @ApiModel
/*    */ public class EncryptedPKCSPackageInput
/*    */ {
/*    */   @ApiModelProperty("The backend subject key identifier. It is sent as Base64 encoded bytes. The length is 20 bytes.")
/*    */   private String backendSubjectKeyIdentifier;
/*    */   @ApiModelProperty("Encrypted PKCS package generated by SigModul.")
/*    */   private String encryptedPKCSPackage;
/*    */   
/*    */   public EncryptedPKCSPackageInput() {}
/*    */   
/*    */   public EncryptedPKCSPackageInput(String backendSubjectKeyIdentifier, String encryptedPKCSPackage) {
/* 41 */     this.encryptedPKCSPackage = encryptedPKCSPackage;
/* 42 */     this.backendSubjectKeyIdentifier = backendSubjectKeyIdentifier;
/*    */   }
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */   
/*    */   public String getEncryptedPKCSPackage() {
/* 51 */     return this.encryptedPKCSPackage;
/*    */   }
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */   
/*    */   public String getBackendSubjectKeyIdentifier() {
/* 60 */     return this.backendSubjectKeyIdentifier;
/*    */   }
/*    */ }


/* Location:              C:\Users\admin\Downloads\Zenzefi\zenzefi-1.96.0.6.jar!\BOOT-INF\lib\common-server-1.96.0.6.jar!\com\daimler\cebas\certificates\control\vo\EncryptedPKCSPackageInput.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */