/*    */ package com.daimler.cebas.common.control;
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ 
/*    */ public enum CEBASProperty
/*    */ {
/* 10 */   VALIDATE_CERTS, DELETE_EXPIRED_CERTS, DELETE_CERTS_SCHEDULE, SHOW_ZENZEFI_ICON,
/* 11 */   USER_ROLE, CERT_SELECTION, LOG_ENTRIES_FETCH_DATE, MAX_AGE_LOGENTRY, MAX_SIZE_LOGENTRY, CERT_TABLE_DETAIL_VIEW_STATE,
/* 12 */   CERT_TABLE_VISIBLE_COLUMNS, CERT_TABLE_COLUMN_ORDER, PAGINATION_MAX_ROWS_PER_PAGE,
/* 13 */   CHECK_PAGINATION_MAX_ROWS_PER_PAGE_MIN, CHECK_PAGINATION_MAX_ROWS_PER_PAGE_MAX,
/* 14 */   LOGOFF_NO_USER_ACTION, LOGGING_LEVEL, BUSINESS_ENVIRONMENT, CHECK_MAX_AGE_LOGENTRY_MIN,
/* 15 */   CHECK_MAX_AGE_LOGENTRY_MAX, CERT_LIFETIME_GREEN_THRESHHOLD, CERT_LIFETIME_YELLOW_THRESHHOLD,
/* 16 */   CHECK_CERT_LIFETIME_GREEN_THRESHHOLD_MIN, CHECK_CERT_LIFETIME_GREEN_THRESHHOLD_MAX,
/* 17 */   CHECK_CERT_LIFETIME_YELLOW_THRESHHOLD_MIN, CHECK_CERT_LIFETIME_YELLOW_THRESHHOLD_MAX,
/* 18 */   SERVER_LOGBACK_FILE, SERVER_LOGBACK_FILENAME_PATTERN, SERVICE_LOG_FOLDER,
/* 19 */   PERFORMANCE_AUDIT_ENTRY_MAX_AGE, CHECK_MAX_AGE_PERFORMANCE_AUDIT_ENTRY_MIN,
/* 20 */   CHECK_MAX_AGE_PERFORMANCE_AUDIT_ENTRY_MAX, PERFORMANCE_AUDIT_CLEANUP_JOB,
/* 21 */   PERFORMANCE_AUDIT_PERSIST_JOB, HTTPS_PROXY_HOST, HTTPS_PROXY_PORT,
/* 22 */   HTTPS_PROXY_TYPE, NUMBER_OF_FAILED_LOGIN_ATTEMPTS,
/* 23 */   CHECK_NUMBER_OF_FAILED_LOGIN_ATTEMPTS_MIN,
/* 24 */   CHECK_NUMBER_OF_FAILED_LOGIN_ATTEMPTS_MAX, SSL_VALIDATION,
/* 25 */   EXCLUDED_CENTRAL_AUTH_ROLES, PERSIST_PERFORMANCE_AUDIT_ENTRY, AUTO_CERT_UPDATE, LOGS_VERSION, LOGS_KEY, LOGS_OLDER_VERSION_USED,
/* 26 */   STATUS_0, STATUS_1, STATUS_2, STATUS_3, ENABLE_PROXY_SETTINGS, AUTOLOGOUT, ENABLE_VIN_ECU_RESTRICTION_CHECK, VALIDITY_CHECK_TIME_TOLERANCE, PKISCOPE_SWITCH;
/*    */ }


/* Location:              C:\Users\admin\Downloads\Zenzefi\zenzefi-1.96.0.6.jar!\BOOT-INF\lib\common-server-1.96.0.6.jar!\com\daimler\cebas\common\control\CEBASProperty.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */