ALTER TABLE ZENZEFI.R_CERTIFICATE DROP COLUMN F_UPDATE_LABEL;
ALTER TABLE ZENZEFI.R_CERTIFICATE ADD f_ecu_package_ts VARCHAR(255);
ALTER TABLE ZENZEFI.R_CERTIFICATE DROP COLUMN F_ASNR;
ALTER TABLE ZENZEFI.R_CERTIFICATE ADD f_zk_no VARCHAR(32);