SET DB_CLOSE_DELAY 10;
SET CACHE_SIZE 6114;
CREATE USER IF NOT EXISTS H2 SALT 'dae457c36837fa92' HASH '7743c474876eea520d686506f4842a522287431701d0daf7670fa83089d6b001' ADMIN;
CREATE SCHEMA IF NOT EXISTS ZENZEFI AUTHORIZATION H2;
CREATE CACHED TABLE ZENZEFI.R_CONFIGURATION( 
    F_ID VARCHAR(36) NOT NULL, 
    F_CREATE_TIMESTAMP TIMESTAMP, 
    F_CREATE_USER VARCHAR(50), 
    F_UPDATE_TIMESTAMP TIMESTAMP, 
    F_UPDATE_USER VARCHAR(50), 
    F_CONFIG_KEY VARCHAR(50) NOT NULL, 
    F_CONFIG_VALUE VARCHAR(600), 
    F_DESCRIPTION VARCHAR(256) 
);
ALTER TABLE ZENZEFI.R_CONFIGURATION ADD CONSTRAINT ZENZEFI.CONSTRAINT_C PRIMARY KEY(F_ID);
CREATE CACHED TABLE ZENZEFI.R_KEY_STORE( 
    F_ID VARCHAR(36) NOT NULL, 
    F_CREATE_TIMESTAMP TIMESTAMP, 
    F_CREATE_USER VARCHAR(50), 
    F_UPDATE_TIMESTAMP TIMESTAMP, 
    F_UPDATE_USER VARCHAR(50), 
    F_PRIVATE_KEY VARCHAR, 
    F_PUBLIC_KEY VARCHAR, 
    R_CERTIFICATE VARCHAR(36), 
    R_USER VARCHAR(36) 
);
ALTER TABLE ZENZEFI.R_KEY_STORE ADD CONSTRAINT ZENZEFI.CONSTRAINT_D PRIMARY KEY(F_ID);
CREATE CACHED TABLE ZENZEFI.R_PERFORMANCE_AUDIT_ENTRY( 
    F_ID VARCHAR(36) NOT NULL, 
    F_CREATE_TIMESTAMP TIMESTAMP NOT NULL, 
    F_CREATE_USER VARCHAR(50) NOT NULL, 
    F_UPDATE_TIMESTAMP TIMESTAMP, 
    F_UPDATE_USER VARCHAR(50), 
    F_DURATION BIGINT NOT NULL, 
    F_PROJECT_REVISION VARCHAR(200) NOT NULL, 
    F_PROJECT_VERSION VARCHAR(50) NOT NULL, 
    F_TARGET_CLASS_NAME VARCHAR(256) NOT NULL, 
    F_TARGET_METHOD_NAME VARCHAR(256) NOT NULL, 
    F_USER_NAME VARCHAR(128), 
    F_CORRELATION_ID VARCHAR(36) 
);
ALTER TABLE ZENZEFI.R_PERFORMANCE_AUDIT_ENTRY ADD CONSTRAINT ZENZEFI.CONSTRAINT_33 PRIMARY KEY(F_ID);
CREATE CACHED TABLE ZENZEFI.R_CERTIFICATE( 
    F_ID VARCHAR(36) NOT NULL, 
    F_CREATE_TIMESTAMP TIMESTAMP, 
    F_CREATE_USER VARCHAR(50), 
    F_UPDATE_TIMESTAMP TIMESTAMP, 
    F_UPDATE_USER VARCHAR(50), 
    F_ACTIVE_FOR_TESTING BOOLEAN, 
    F_ALGORITHM_IDENTIFIER VARCHAR(255), 
    F_AUTHORITY_KEY_IDENTIFIER VARCHAR(120), 
    F_BASE_CERTIFICATE_ID VARCHAR(255), 
    F_BASIC_CONSTRAINTS VARCHAR(255), 
    F_DATA BLOB, 
    F_ISSUER VARCHAR(50), 
    F_ISSUER_SERIAL_NUMBER VARCHAR(100), 
    F_KEY_USAGE BINARY(50), 
    F_NONCE VARCHAR(150), 
    F_PROD_QUALIFIER VARCHAR(50), 
    F_SERIAL_NO VARCHAR(100), 
    F_SERVICES VARCHAR, 
    F_SIGNATURE VARCHAR, 
    F_SPECIAL_ECU VARCHAR(30), 
    F_STATE VARCHAR(30), 
    F_SUBJECT VARCHAR(50), 
    F_SUBJECT_KEY_IDENTIFIER VARCHAR(120), 
    F_SUBJECT_PUBLIC_KEY VARCHAR(150), 
    F_TARGET_ECU VARCHAR, 
    F_TARGET_SUBJECT_KEY_IDENTIFIER VARCHAR(120), 
    F_TARGET_VIN VARCHAR, 
    F_CERTIFICATE_TYPE VARCHAR(100), 
    F_ECU_ID VARCHAR, 
    F_USER_ROLE VARCHAR(255), 
    F_VALID_FROM TIMESTAMP, 
    F_VALID_TO TIMESTAMP, 
    F_VERSION VARCHAR(20), 
    R_CERTIFICATE_PARENT VARCHAR(36), 
    F_USER_ID VARCHAR(36), 
    VALIDITY_STRENGTH_COLOR VARCHAR(50), 
    DTYPE VARCHAR(50), 
    F_PKCS10_SIGNATURE CLOB 
);
ALTER TABLE ZENZEFI.R_CERTIFICATE ADD CONSTRAINT ZENZEFI.CONSTRAINT_3 PRIMARY KEY(F_ID);

CREATE INDEX ZENZEFI.PARENT_ID_INDEX ON ZENZEFI.R_CERTIFICATE(R_CERTIFICATE_PARENT);
CREATE INDEX ZENZEFI.SERIAL_NO_INDEX ON ZENZEFI.R_CERTIFICATE(F_SERIAL_NO);
CREATE INDEX ZENZEFI.AKI_INDEX ON ZENZEFI.R_CERTIFICATE(F_AUTHORITY_KEY_IDENTIFIER);
CREATE INDEX ZENZEFI.SKI_INDEX ON ZENZEFI.R_CERTIFICATE(F_SUBJECT_KEY_IDENTIFIER);
CREATE INDEX ZENZEFI.CERTIFICATE_TYPE_INDEX ON ZENZEFI.R_CERTIFICATE(F_CERTIFICATE_TYPE);
CREATE CACHED TABLE ZENZEFI.R_USER( 
    F_ID VARCHAR(36) NOT NULL, 
    F_CREATE_TIMESTAMP TIMESTAMP, 
    F_CREATE_USER VARCHAR(50), 
    F_UPDATE_TIMESTAMP TIMESTAMP, 
    F_UPDATE_USER VARCHAR(50), 
    F_USER_FIRST_NAME VARCHAR(255), 
    F_USER_LAST_NAME VARCHAR(255), 
    F_USER_ORGANISATION VARCHAR(255), 
    F_USER_ROLE INTEGER, 
    F_SALT VARCHAR(255), 
    F_USER_NAME VARCHAR(255), 
    F_USER_PASSWORD VARCHAR(255), 
    F_NUMBER_OF_FAILED_LOGINS INTEGER, 
    DTYPE VARCHAR(50) 
);
ALTER TABLE ZENZEFI.R_USER ADD CONSTRAINT ZENZEFI.CONSTRAINT_9 PRIMARY KEY(F_ID);

CREATE INDEX ZENZEFI.F_USER_NAME_INDEX ON ZENZEFI.R_USER(F_USER_NAME);
CREATE CACHED TABLE ZENZEFI.R_USER_CERTIFICATES( 
    USER_F_ID VARCHAR(36) NOT NULL, 
    CERTIFICATES_F_ID VARCHAR(36) NOT NULL 
);
CREATE CACHED TABLE ZENZEFI.R_USER_CONFIGURATIONS( 
    USER_F_ID VARCHAR(36) NOT NULL, 
    CONFIGURATION_F_ID VARCHAR(36) NOT NULL 
);

CREATE CACHED TABLE ZENZEFI.R_LOG( 
    F_ID VARCHAR(36) NOT NULL, 
    F_CREATE_TIMESTAMP TIMESTAMP, 
    F_CREATE_USER VARCHAR(50), 
    F_UPDATE_TIMESTAMP TIMESTAMP, 
    F_UPDATE_USER VARCHAR(50), 
    F_CHECKSUM VARCHAR NOT NULL, 
    F_MESSAGE VARCHAR NOT NULL, 
    F_TYPE VARCHAR(50) NOT NULL, 
    F_LOG_ENTRY_ID VARCHAR(36), 
    F_PREFERRED_CHECKSUM VARCHAR 
);
ALTER TABLE ZENZEFI.R_LOG ADD CONSTRAINT ZENZEFI.CONSTRAINT_4 PRIMARY KEY(F_ID);

CREATE INDEX ZENZEFI.F_CREATE_TIMESTAMP_INDEX ON ZENZEFI.R_LOG(F_CREATE_TIMESTAMP);
CREATE INDEX ZENZEFI.F_CHECKSUM_INDEX ON ZENZEFI.R_LOG(F_CHECKSUM);
CREATE INDEX ZENZEFI.F_TYPE_INDEX ON ZENZEFI.R_LOG(F_TYPE);
CREATE INDEX ZENZEFI.F_LOG_ENTRY_ID_INDEX ON ZENZEFI.R_LOG(F_LOG_ENTRY_ID);
ALTER TABLE ZENZEFI.R_USER_CONFIGURATIONS ADD CONSTRAINT ZENZEFI.UK_2OWKJXK4V6O630LRC5XJL3SUN UNIQUE(CONFIGURATION_F_ID);
ALTER TABLE ZENZEFI.R_USER_CERTIFICATES ADD CONSTRAINT ZENZEFI.UK_P4MB6XV0GHCAP8YWTNVW853CE UNIQUE(CERTIFICATES_F_ID);
ALTER TABLE ZENZEFI.R_CERTIFICATE ADD CONSTRAINT ZENZEFI.FKFBN036I5RMAEY3VRHW863K6L9 FOREIGN KEY(R_CERTIFICATE_PARENT) REFERENCES ZENZEFI.R_CERTIFICATE(F_ID) NOCHECK;
ALTER TABLE ZENZEFI.R_KEY_STORE ADD CONSTRAINT ZENZEFI.FKM62Q5Y22A08RHPIGYJAX8NQ0V FOREIGN KEY(R_USER) REFERENCES ZENZEFI.R_USER(F_ID) NOCHECK;
ALTER TABLE ZENZEFI.R_USER_CERTIFICATES ADD CONSTRAINT ZENZEFI.FKHBOXYPWL74G62S2P2L9GLVK8 FOREIGN KEY(CERTIFICATES_F_ID) REFERENCES ZENZEFI.R_CERTIFICATE(F_ID) NOCHECK;
ALTER TABLE ZENZEFI.R_KEY_STORE ADD CONSTRAINT ZENZEFI.FK5UYO8XT3IEI3I6S7BIM0AV2XR FOREIGN KEY(R_CERTIFICATE) REFERENCES ZENZEFI.R_CERTIFICATE(F_ID) NOCHECK;
ALTER TABLE ZENZEFI.R_CERTIFICATE ADD CONSTRAINT ZENZEFI.FK1YEHHT208WR1G9IGNH0GF1PV2 FOREIGN KEY(F_USER_ID) REFERENCES ZENZEFI.R_USER(F_ID) NOCHECK;
ALTER TABLE ZENZEFI.R_LOG ADD CONSTRAINT ZENZEFI.FKR4G7YOWWGJ3YR8BGS46DCDXUE FOREIGN KEY(F_LOG_ENTRY_ID) REFERENCES ZENZEFI.R_LOG(F_ID) NOCHECK;
ALTER TABLE ZENZEFI.R_USER_CONFIGURATIONS ADD CONSTRAINT ZENZEFI.FK5EU5H4IYC88STBQV8QHPTWOG FOREIGN KEY(CONFIGURATION_F_ID) REFERENCES ZENZEFI.R_CONFIGURATION(F_ID) NOCHECK;
ALTER TABLE ZENZEFI.R_USER_CERTIFICATES ADD CONSTRAINT ZENZEFI.FKE1F9HJL67LASMQU7BM6ISMFGX FOREIGN KEY(USER_F_ID) REFERENCES ZENZEFI.R_USER(F_ID) NOCHECK;
ALTER TABLE ZENZEFI.R_USER_CONFIGURATIONS ADD CONSTRAINT ZENZEFI.FK6TIT5510F1BC5R7KL8JXHK1N FOREIGN KEY(USER_F_ID) REFERENCES ZENZEFI.R_USER(F_ID) NOCHECK;