UPDATE ZENZEFI.R_CONFIGURATION SET F_CONFIG_VALUE = 'default' WHERE f_config_key = 'CERT_TABLE_VISIBLE_COLUMNS';
UPDATE ZENZEFI.R_CONFIGURATION SET F_CONFIG_VALUE = 'default' WHERE f_config_key = 'CERT_TABLE_COLUMN_ORDER';

