UPDATE ZENZEFI.R_CONFIGURATION SET F_CONFIG_VALUE = 'default' WHERE f_config_key = 'CERT_TABLE_VISIBLE_COLUMNS';
UPDATE ZENZEFI.R_CONFIGURATION SET F_CONFIG_VALUE = 'default' WHERE f_config_key = 'CERT_TABLE_COLUMN_ORDER';
ALTER TABLE ZENZEFI.R_CERTIFICATE ADD F_STATUS VARCHAR;
UPDATE ZENZEFI.R_CERTIFICATE SET F_STATUS = '1' WHERE F_STATE = 'ISSUED';
UPDATE ZENZEFI.R_CERTIFICATE SET F_STATUS = '0' WHERE F_STATE = 'SIGNING_REQUEST';