/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  io.swagger.annotations.ApiModel
 *  io.swagger.annotations.ApiModelProperty
 */
package com.daimler.cebas.certificates.control.vo;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

@ApiModel
public class EncryptedPKCSPackageInput {
    @ApiModelProperty(value="The backend subject key identifier. It is sent as Base64 encoded bytes. The length is 20 bytes.")
    private String backendSubjectKeyIdentifier;
    @ApiModelProperty(value="Encrypted PKCS package generated by SigModul.")
    private String encryptedPKCSPackage;

    public EncryptedPKCSPackageInput() {
    }

    public EncryptedPKCSPackageInput(String backendSubjectKeyIdentifier, String encryptedPKCSPackage) {
        this.encryptedPKCSPackage = encryptedPKCSPackage;
        this.backendSubjectKeyIdentifier = backendSubjectKeyIdentifier;
    }

    public String getEncryptedPKCSPackage() {
        return this.encryptedPKCSPackage;
    }

    public String getBackendSubjectKeyIdentifier() {
        return this.backendSubjectKeyIdentifier;
    }
}
